services:
  api:
    build: .
    container_name: node-http-users-api

    volumes:
      - api-data:/app/data

    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: node-http-users-caddy

    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

    restart: unless-stopped

    depends_on:
      - api

volumes:
  api-data:
  caddy-data:
  caddy-config: